GET http://localhost:3000/users

?? status == 200

HTTP/1.1 200  - OK
content-type: application/json
content-length: 1236
connection: close
date: Sat, 17 May 2025 07:14:08 GMT
###
POST http://localhost:3000/users
Content-Type: application/json
{
    "name": "Johccdsdsn Doe 2KK",
    "email": "johncsKcdsKK.doe@examp2le.com",
    "password": "password123",
    "is_active": true
}

?? status == 201

HTTP/1.1 201  - Created
content-type: application/json
content-length: 150
connection: close
date: Sat, 17 May 2025 06:32:45 GMT