GET http://localhost:3000/users

?? status == 200

HTTP/1.1 200  - OK
content-type: application/json
content-length: 675
connection: close
date: Sat, 17 May 2025 05:24:59 GMT
###
POST http://localhost:3000/users
Content-Type: application/json
{
    "name": "John Doe 2KK",
    "email": "johnKKK.doe@examp2le.com",
    "password": "password123",
    "is_active": true
}

?? status == 201

HTTP/1.1 201  - Created
content-type: application/json
content-length: 139
connection: close
date: Sat, 17 May 2025 05:25:15 GMT